### ISSUE TITLE
Можно ли использовать данный пакет в продакшен?

### ISSUE THREAD

**Issue by YadrovSergey** [tarantool-php/client#10]
Использует ли кто-нибудь данный пакет в продакшен?

Есть конечно официальный пакет https://github.com/tarantool/tarantool-php
Но он не работает пока на php7.

**Comment by kamenevn** [comment]
Мы используем, пока нечего криминально не было, но при этом кроме update/insert/delete/select
не делаем.

https://github.com/tarantool/tarantool-php - есть ветка с поддержкой php7, но работает не стабильно

**Comment by rybakit** [comment]
Насколько я знаю, @nekufa использует этот пакет в продакшене.

**Comment by nekufa** [comment]
Да, мы мы используем клиента с SocketConnection и PurePacker.
Поверх него используется mapper, который создаёт спейсы, индексы, удаляет их (у нас миграции на php). Наш кейс покрывает практически весь функционал клиента.
Если есть вопросы - обращайтесь в http://telegram.me/nekufa либо на почту nekufa@gmail.com

**Comment by YadrovSergey** [comment]
Спасибо.
