### ISSUE TITLE
Array indexes are changed

### ISSUE THREAD

**Issue by nekufa** [tarantool-php/client#16]
I use this code to calculate something in lua grouped by integer key
```
var_dump($client->evaluate('
    local result = {}
    result[8] = 15
    return result
')->getData());
```
Running the code will provide this result.
Please note that index was decreased by one.
```
array(1) {
  [0]=>
  array(8) {
    [0]=>
    NULL
    [1]=>
    NULL
    [2]=>
    NULL
    [3]=>
    NULL
    [4]=>
    NULL
    [5]=>
    NULL
    [6]=>
    NULL
    [7]=>
    int(15)
  }
}
```

I found workaround - initialize with non-integer key, so the result keeps good:
```
var_dump($client->evaluate('
    local result = {_ = 0}
    result[8] = 15
    return result
')->getData());
```
This way i see expected result.
```
array(1) {
  [0]=>
  array(2) {
    [8]=>
    int(15)
    ["_"]=>
    int(0)
  }
}
```

Maybe there is a way to keep it working without any workaround?
For example, change indexes only when all keys are integer, goes one by one and last equals table size.

**Comment by rybakit** [comment]
@nekufa The similar issue is discussed here: https://github.com/tarantool/tarantool-php/issues/89

**Comment by rybakit** [comment]
> Maybe there is a way to keep it working without any workaround?
> For example, change indexes only when all keys are integer, goes one by one and last equals table size.

I don't think it should be fixed on the client side. It looks like a Tarantool issue to me, the client receives `MP_ARRAY` of 8 items instead of `MP_MAP` in a response. I guess Tarantool should check if a lua table is an array and pack it accordingly.

**Comment by rybakit** [comment]
As discussed on Tarantool chat, to force Tarantool to pack in to map/array structures you need to specify the  [__serialize](https://tarantool.org/doc/1.7/reference/reference_lua/msgpack.html?highlight=__serialize#example) hint:

```php
print_r($client->evaluate('
    local result = {}
    result[8] = 15
    return result
')->getData());

print_r($client->evaluate('
    local result = setmetatable({}, { __serialize = "map" })
    result[8] = 15
    return result
')->getData());
```

Output:

```
Array
(
    [0] => Array
        (
            [0] =>
            [1] =>
            [2] =>
            [3] =>
            [4] =>
            [5] =>
            [6] =>
            [7] => 15
        )

)
Array
(
    [0] => Array
        (
            [8] => 15
        )

)
```

**Comment by nekufa** [comment]
Thanks
