### ISSUE TITLE
Need client for older PHP versions.

### ISSUE THREAD

**Issue by ethaniel** [tarantool-php/client#20]
I use PHP 5.3.3 and would prefer a client as a standalone class (without composer).
I assume that alot of people would agree with me.

**Comment by rybakit** [comment]
The active support by the PHP project for PHP 5.6 ended a month ago, so it doesn't make any sense to me to support the client for even older versions. I would strongly recommend you to upgrade to the latest PHP versions. Regarding the composer, it's not a requirement and you can just download a zip file from [this page](https://github.com/tarantool-php/client/releases), extract it and use with your own autoloader. But again, I see no reason to not use composer.

**Comment by ethaniel** [comment]
People who are using Centos 6 (which is rock solid and still supported) have still php 5.3.3 installed by default.

**Comment by rybakit** [comment]
There are a few options you may consider:
1) Install a newer php version on centos 6
2) Check the PECL's tarantool extension if it can be run on 5.3
3) Fork this library and make it compatible with 5.3

I'm closing this as I don't have enough time and interest in supporting EOL versions.
