### ISSUE TITLE
Add "truncate" request

### ISSUE THREAD

**Issue by icamys** [tarantool-php/client#26]
It would be nice to add a method that allows space truncation. Is there any chance this request type would be implemented?

**Comment by rybakit** [comment]
Currently, the library implements all requests specified by the [IPROTO protocol](https://tarantool.org/doc/1.7/dev_guide/internals_index.html#unified-packet-structure). There a lot of [other methods](https://tarantool.org/doc/1.7/book/box/box_space.html) available for spaces and I beleive that adding `truncate` and skipping others will mislead users. Therefore, the library needs to either support all these box-level requests or only low-level IPROTO ones.  I prefer the latter.

**Comment by icamys** [comment]
@rybakit Thanks for your explanation. Could you advice a more high-level library that works currently with php7?

**Comment by rybakit** [comment]
I doubt that such a high-level library exists. What is your use case? Do you know that you can call `truncate` via `call` or `eval`? Here is a copy-paste from README:

```php
$result = $client->call('box.stat');
var_dump($result->getData());
```

**Comment by icamys** [comment]
@rybakit Just few minutes ago found out and encountered another issue:

```
Create or drop access denied for user 'username'
```

Here's my config:
```lua
if box.schema.user.exists('username') == false then
    box.schema.user.create('username', { password = 'userpass' })
    box.schema.user.grant('username', 'replication')
    box.schema.user.grant('username', 'read,write,execute', 'universe')
end
```

Looks like it's [tarantool engines issue](https://github.com/tarantool/tarantool/issues/945).

**Comment by rybakit** [comment]
> Looks like it's tarantool engines issue.

Yep, it's not related to this repository, so I guess your issue can be closed?

**Comment by icamys** [comment]
Yep
