### ISSUE TITLE
Add some more docs

### ISSUE THREAD

**Issue by icamys** [tarantool-php/client#27]
It would be nice to add some more docs on how to use the client. I.e.: what parameters should be passed to upsert method. Personally I have not found proper way to upsert data

**Comment by rybakit** [comment]
I agree that the library lacks documentation and will appreciate any help with writing more docs. In a meanwhile you can check tests to see how to use api, e.g. here is a test for upsert: https://github.com/tarantool-php/client/blob/master/tests/Integration/SpaceTest.php#L133-L151

**Comment by icamys** [comment]
Hi @rybakit ! Thank you for your response. Could you please give me a tip on what means `[[ ':', 1, 0, 1,  'U ]]` in [$operation variable](https://github.com/tarantool-php/client/blob/master/tests/Integration/SpaceTest.php#L139).

In [official docs](https://tarantool.org/ru/doc/1.7/book/box/box_space.html?highlight=upsert#lua-функция.space_object.upsert) I found out that operation should consist out of 3 parts: `operator`, `field_no` and `value`, but in the test there are unexpected 5 parts (`':'`, `1`, `0`, `1`, `'U'` respectively). Is there any explanation what these parts stand for?

UPDATE:
`':'` - is operator. Full list of operators found [here](https://tarantool.org/ru/doc/1.7/book/box/box_space.html?highlight=upsert#lua-функция.space_object.update).

UPDATE 2:
Found the explanation in [official docs](https://tarantool.org/ru/doc/1.7/book/box/box_space.html?highlight=upsert#lua-функция.space_object.update) in last example.

**Comment by rybakit** [comment]
@icamys the number of arguments depends on the type of the operator, so, `=` (assignment) needs 3 parts, but the splice operator (`:`) requires 5 parts, iirc: _operator_, _field_no_, _start_index_, _length_, _new_substr_.

**Comment by icamys** [comment]
@rybakit Thanks for the explanation. I created a pull request with some examples of using inserting/upserting.

**Comment by rybakit** [comment]
> I created a pull request

Where?

**Comment by icamys** [comment]
[Here](https://github.com/tarantool-php/client/pull/28) it is. Looks like I've mixed up target repo first time.

**Comment by icamys** [comment]
Closing the issue as [PR](https://github.com/tarantool-php/client/pull/28) is merged.

**Comment by icamys** [comment]
Closing the issue as [PR](https://github.com/tarantool-php/client/pull/28) is merged.
