### ISSUE TITLE
Support lazy authentication

### ISSUE THREAD

**Issue by rybakit** [tarantool-php/client#32]
1)
```php
$conn = new StreamConnection('tcp://127.0.0.1:3301', [
    'username' => 'username',
    'password' => 'password',
]);
$client = new Client($conn, new PurePacker());
```

2)
```php
$conn = new StreamConnection('tcp://127.0.0.1:3301');
$client = new Client($conn, new PurePacker(), [
    'username' => 'username',
    'password' => 'password',
]);
```

3)
```php
$conn = new StreamConnection('tcp://127.0.0.1:3301');
$client = new Client($conn, new PurePacker());
$client->setCredentials('username', 'password'); // <- lazy
$client->authenticate('username', 'password'); // <- non-lazy
```

**Comment by nekufa** [comment]
I think that client should authenticate using connection.  So, first option looks not good for me.
Third one is the best - in some cases i want to test credentials right now and don't want to call ping, for example.

**Comment by rybakit** [comment]
Tend to agree that 1) is a bad choice. 3) looks like a winner, the only thing that makes me worry is that it might not be clear enough from just reading the code how `setCredentials()` differs from `authenticate()`. But it's more of a naming issue.

**Comment by rybakit** [comment]
Another option:

3.1

```php
$client->setCredentials('foo', 'foo');
$client->authenticate();
```
instead of

```php
$client->setCredentials('foo', 'foo');
$client->authenticate('bar', 'bar');
```

**Comment by nekufa** [comment]
Yep, sounds good! I think 3.1 is the best choice.  
You have one way to set username and password and can authenticate on demand.

**Comment by rybakit** [comment]
@nekufa There is one thing about 3.1 that bothers me: you have to call `setCredentials($user, $pass)` before calling `authenticate()`, otherwise `authenticate()` will throw a LogicException. Because of that, now I'm more inclined to the 2nd option (2.1):

```php
$client = new Client($conn, new PurePacker(), [ // lazy
    'username' => 'username',
    'password' => 'password',
]);
$client->authenticate('username', 'password'); // <- non-lazy
```

With this approach we always have a fully initialized client object and still can force authentication if needed. What do you think?

**Comment by rybakit** [comment]
Fixed via https://github.com/tarantool-php/client/pull/37.
