### ISSUE TITLE
Add iterator types

### ISSUE THREAD

**Issue by nekufa** [tarantool-php/client#33]
Add iterator types constants.
Example: https://github.com/tarantool/tarantool-php#predefined-constants

Maybe, they should be placed in any given class:
- Tarantool\Client\Schema\Index
- Tarantool\Client\Request\SelectRequest

**Comment by yaBliznyk** [comment]
Where is values for this constants?

**Comment by rybakit** [comment]
As mentioned in the telegram chat, constants values are listed here: https://github.com/tarantool/tarantool/blob/2.0/src/box/iterator_type.h#L62-L77.

**Comment by rybakit** [comment]
Fixed via https://github.com/tarantool-php/client/pull/35.
