### ISSUE TITLE
Docs needs to be updated

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#38]
Hi,
it seems that the docs or guide regarding using SELECT doesnt return the column names, instead it is an array with integer indexes. 

`$result3 = $client->executeQuery('SELECT * FROM users WHERE email = ?', 'foobar@example.com');
printf("Result 3: %s\n", json_encode(iterator_to_array($result3)));`

So the code above gives me:
`Result 3: [{"0":1,"1foobar@example.com"}]`

Instead of 
`Result 3: [{"ID":1,"EMAIL":"foobar@example.com"}]`

Thanks if you can fix this.

**Comment by zilveer** [comment]
Please see #39 , I just made a push and solved the issue

**Comment by rybakit** [comment]
@zilveer Can this issue be closed as well?

**Comment by zilveer** [comment]
@rybakit
Yes it can thanks
