### ISSUE TITLE
Column names to lower case as default? 

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#40]
Hi,
Thanks for a great plugin.
Is it possible to have an option or make it default for column names to lower case or case insensitive?

Regards

**Comment by rybakit** [comment]
This is an issue of the Tarantool SQL implementation, which they plan to fix. As for now, as a workaround,  you may wrap column names in double quotes to get the desired result. I've updated README and the [execute](https://github.com/tarantool-php/client/blob/d4dc6803c1709c3dd31d32a99fe8c5ed73f685a2/examples/protocol/execute.php) example.
