### ISSUE TITLE
Methods such as findOrFail, saveOrFail, updateOrFail

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#41]
Hi,
is it possible to add Methods such as findOrFail, saveOrFail, updateOrFail etc to this great plugin ?

Regards

**Comment by zilveer** [comment]
Maybe also methods such as save(), update (), find() etc..?
;)

**Comment by rybakit** [comment]
I wonder if you've seen the [mapper](https://github.com/tarantool-php/mapper) library? It's built on top of this client and already has what you are asking, eg: https://github.com/tarantool-php/mapper/blob/e8290dc92469e9ef35c53be7a85a6caea23095d9/src/Mapper.php#L48-L66 /cc @nekufa

**Comment by zilveer** [comment]
@rybakit
Yes I have seen it and tested it as well.
But it doesnt work well with SQL syntaxes.

And besides I think implementation of such functions I mentioned above should be in the base repo and not by extending this package with php mapper even though I like php mapper it doesn't seem to be really tested with SQL syntaxes. 

Cannot we just apply those functions in the php client ?
I can help with adding the functions and make commits ?

**Comment by rybakit** [comment]
I'm not sure what is the purpose of this. You already have a bunch of methods to work with data, like insert, update, replace, upsert etc, so I don't see why you need to reimplement them via SQL statements, this will not give any benefit. "-orFail" doesn't make much sense either, as all these methods throw on error.

It would make sense if you write a new adapter for the existing interfaces which work with SQL, for example, a new Tarantool driver for [doctrine/dbal](https://github.com/doctrine/dbal). But then, it's out of the scope of the client and should be implemented in another repository anyway.

**Comment by zilveer** [comment]
@rybakit yeah it is only actually about themethod naming, I thought that maybe many others would adapt the package.

regards
