### ISSUE TITLE
Return only first array in a query ? 

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#42]
Hello, when using SELECT query is it possible for you to code to the iterator only returns the first array instead of an array with an subarray to the found row?

I want to make it simple and do this (when only 1 row is found )

`echo $person['name']`
Instead of 
`echo $person[0]['name']`

Regards

**Comment by rybakit** [comment]
Could you show an example of the data you have and how you retrieve it?

**Comment by rybakit** [comment]
I've [added](https://github.com/tarantool-php/client/commit/5aa52f0f1a61c943df05291cdf69330a3764074f) the following methods to `SqlQueryResult`:

```php
public function isEmpty() : bool
public function getFirst() : ?array
public function getLast() : ?array
public function count() : int
```

**Comment by zilveer** [comment]
@rybakit sorry for the delay,

This is what Im doing:
```
$sqlQ = $client->executeQuery("SELECT * FROM POSTS WHERE USER_ID = 21");
$posts= iterator_to_array($sqlQ);

var_dump($posts);
```
and this is the result:
```
array (size=1)
  0 => 
    array (size=7)
      'id' => int 4
      'user_id' => int 21
      'likes' => int 18
      'comments' => int 6
```

and this is how I solved it:
```
$getRows = iterator_to_array($query);
$totalRows = count($getData);
if($totalRows){
    if($totalRows == 1){
        return $getFirstRow = $getRows[0];
    }else{
        $getAllRows = $getRows;
        return $getAllRows;
    }
}
```
Perhaps I can make a commit with some suggestions which I think is good to have? For example adding my solution to the `SqlQueryResult` as an method would be good. 
I am more then willing to make commits if that is okey?

**Comment by zilveer** [comment]
> 
> 
> I've [added](https://github.com/tarantool-php/client/commit/5aa52f0f1a61c943df05291cdf69330a3764074f) the following methods to `SqlQueryResult`:
> 
> ```
> public function isEmpty() : bool
> public function getFirst() : ?array
> public function getLast() : ?array
> public function count() : int
> ```

This is great, thanks.
