### ISSUE TITLE
SQL injections in Tarantool?

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#43]
Hi,
I have a question and that is do you do anything to prevent SQL injections ?
I wanted to use the PDO bindparams but it seems that it is specifically bounded to mySQL.
Perhaps taking that method and implementing it in this package would be good?

Any feedback is appreciated.
regards

**Comment by rybakit** [comment]
To prevent SQL injections you should send data separately from the query string. 

With PDO:

```php
$stmt = $pdo->prepare('UPDATE users SET name = :name WHERE id = :id');
$result = $stmt->execute([':name' => 'Foobar', ':id' => $id]);
```
With the client:

```php
$result = $client->executeUpdate('UPDATE users SET name = :name WHERE id = :id', 
    [':name' => 'Foobar'], [':id' => $id]
);
```

And just like in PDO, you can use named (`:name`) or positional (`?`) parameters:

```php
$result = $client->executeUpdate('DELETE FROM users WHERE id = ?', $id);
```

**Comment by zilveer** [comment]
Oh thx for a quick and prompt reply!

How will it work with a query condition with an IN clause?

**Comment by rybakit** [comment]
The same, 

```php
$result = $client->executeUpdate('SELECT * FROM users WHERE "id" IN (?, ?, ?)', 1, 2, 3);
```

**Comment by zilveer** [comment]
Gr8!
Thx please prefer to add this to the SQL docs ;)

**Comment by rybakit** [comment]
I've updated the sql example.

**Comment by zilveer** [comment]
Perfect thx for your hard work !
:)
