### ISSUE TITLE
Slow performance when used in Php

### ISSUE THREAD

**Issue by jobs-git** [tarantool-php/client#44]
Its as simple as this, in php
```php
$mysql = new Tarantool('127.0.0.101', 3301,'guest');
$val = $mysql->select('table',8);
```
I am expecting to get at least 60k req/s if I use c/c++ (async not compatible with http = 1 http req+hugely multiple database req), but In php only got 900 req/s (1http req+1database req). If I use mysql in pool mode in php (1http req+1database req), I can get around 6k req/s. So with tarantool-php its about 6x slower.

However, database usage performance on mysql vs tarantool, tarantool wins hands down (even when conditions are the same like: number of request processed+size of database)

What I can consider as "not slow" is if, tarantool-php can achieve around 60k req/s if impossible, maybe faster than mysql. I tried to use pool for tarantool-php but there is no improvement.

**Comment by rybakit** [comment]
Could you elaborate on how you got to this conclusion? I need more info, like in what environment you run the client, what operations it performs, what results do you get and what results would you consider as "not slow"?

**Comment by jobs-git** [comment]
I have updated the post, I hope I was able to clarify it.

**Comment by rybakit** [comment]
Looks like you are using the [official php connector](https://github.com/tarantool/tarantool-php/) to which this repository has nothing to do. So better to file an issue there. 

For the record, recently I was playing with [swoole](https://github.com/swoole/swoole-src) and [ext-async](https://github.com/concurrent-php/ext-async) and was able to achieve ~52k rps (i only tested inserts) without any modifications of this client. Here is my benchmark script: https://gist.github.com/rybakit/f03c2515a203518126c5479954c5fefb.

**Comment by jobs-git** [comment]
That is an interesting result! At least the performance is close to c/c++. I am closing this now and filing the issue to the connector

**Comment by jobs-git** [comment]
Question though, the benchmark you did was testing the rps of the database. 

In actual web applications, one database request is traced to one http request. The issue with this is the http request waits for the reply from the tarantool database and it will take longer since tarantool batches the requests, thus I get only 900 req/s for http requests from clients.

Do you have a php code that overcomes this to get at most 52k rps http?

**Comment by rybakit** [comment]
Take a look at this link: https://hackernoon.com/tarantool-stress-testing-1195f33254f9
