### ISSUE TITLE
ER_INVALID_MSGPACK: Invalid MsgPack - packet body

### ISSUE THREAD

**Issue by mikkiek** [tarantool-php/client#45]
Hello,

Not sure if it's correct place to post the issue, however I will try.
I've following: 

**Environment** 
1. Tarantool 2.2.0-0-gb58001013 (docker container)
2. PHP-FRM 7.2.18  (docker container)
3. Composer package rybakit/msgpack
4. Composer package tarantool/client

**Code**
```
use \Tarantool\Client\{ Client };

$client = Client::fromOptions([
	'uri' => 'tcp://tarantool:3301',
	'username' => 'mydebug',
	'password' => 'mypassword1!',
]);

$result = $client->executeUpdate('
    CREATE TABLE users ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255))
');

var_dump($result);
```

**Result**
> [Tarantool\Client\Exception\RequestFailed] 
> lid MsgPack - packet body (20)

**Tarantool**
> 2019-05-31 11:04:12.157 [1] iproto iproto.cc:737 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet length
> 2019-05-31 11:04:14.953 [1] iproto xrow.c:174 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:04:16.262 [1] iproto xrow.c:166 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:04:17.874 [1] iproto xrow.c:174 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:04:19.223 [1] iproto xrow.c:166 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:09:38.632 [1] iproto xrow.c:166 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:09:38.632 [1] iproto iproto.cc:737 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet length
> 2019-05-31 11:09:54.434 [1] iproto xrow.c:166 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
> 2019-05-31 11:14:30.

Any ideas or suggestions how to debug or fix it?

Thank you.

**Comment by rybakit** [comment]
What happens if you run [examples/protocol/execute.php](https://github.com/tarantool-php/client/blob/master/examples/protocol/execute.php)? Or try first with `$client->ping()` and check if it succeeds.

**Comment by mikkiek** [comment]
@rybakit 

Sadly $client->ping() doesn't work too.
**PHP**
[Tarantool\Client\Exception\RequestFailed] 
lid MsgPack - packet body (20)
**Tarantool**
2019-05-31 11:57:17.550 [1] iproto xrow.c:174 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body
2019-05-31 11:57:43.571 [1] iproto xrow.c:174 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body

**Comment by rybakit** [comment]
Hmm, all client tests pass on all supported Tarantool versions, including the latest 2.2.0: https://travis-ci.org/tarantool-php/client/jobs/539337099#L878. This makes me think that something is misconfigured on your side. Could you show your init lua script or, ideally, provide a full reproducer including a dockerfile (or/and docker-compose), php and lua scripts?

**Comment by mikkiek** [comment]
Not sure if it could help and easy to use, but i've published my docker-compose and all related files to https://github.com/mikkiek/tarantool-php-issue-55
As you can see, i'm using default tarantool 2.2.0, though php-fpm based on default image but has a lot additional modules

**Comment by rybakit** [comment]
I was able to reproduce the error using your docker-compose. The problem is with the `mbstring.func_overload = 2` setting in `/usr/local/etc/php/php.ini`. When you disable this line or run your script in cli mode with the `-n` flag, everything just works. Note that mbstring function overloading is [deprecated](https://www.php.net/manual/en/mbstring.overload.php) as of PHP 7.2.0.

**Comment by mikkiek** [comment]
Thank you for answer. I will think what can i do with it (mbstring.func_overload hardly can effect on it)
And last question: Does exist any way to run your code with mbstring.func_overload = 2?
Thank you!

**Comment by rybakit** [comment]
> Does exist any way to run your code with mbstring.func_overload = 2?

You may try creating a packer which will de-activate this setting while packing/unpacking packets (not tested):

```php
final class MbstringOverloadedPacker implements Packer
{
    private $packer;
    
    public function __construct(Packer $packer)
    {
        $this->packer = $packer;
    }
 
    public function pack(Request $request, ?int $sync = null) : string
    {
        $funcOverload = ini_get('mbstring.func_overload');
        ini_set('mbstring.func_overload', 0);

        try {
            return $this->packer->pack($request, $sync);
        } finally {
            ini_set('mbstring.func_overload', $funcOverload);
        }
    }

    public function unpack(string $data) : Response
    {
        $funcOverload = ini_get('mbstring.func_overload');
        ini_set('mbstring.func_overload', 0);

        try {
            return $this->packer->unpack($data);
        } finally {
            ini_set('mbstring.func_overload', $funcOverload);
        }
    }
}
```

And then wrap a regular packer and build a client object from [scratch](https://github.com/tarantool-php/client#custom-build):

```php

$packer = new MbstringOverloadedPacker(new PurePacker());
...
$handler = new DefaultHandler($connection, $packer);
$client = new Client($handler);
$client = $client->withMiddleware(new AuthMiddleware('<username>', '<password>'));
```

**Comment by mikkiek** [comment]
Hello,

Unfortunatelly, the 'mbstring.func_overload' setting impossible to set in a PHP code. 
However, I've found a workaround playing with _\mb_internal_encoding('8bit');_ for pack\unpack. Also a small change required inside of Greeting class:
`$salt = \substr($salt, 0, 20);`
replace with
`$salt = \mb_substr($salt, 0, 20, '8bit');`
And then it start working, anyway partially...

For example:
```
$result = $client->evaluate('return box.info.memory()');
var_dump($result);
```
Returns:
> array(1) {
>   [0]=>
>   array(6) {
>     ["cache"]=>
>     int(0)
>     ["data"]=>
>     int(8576)
>     ["tx"]=>
>     int(0)
>     ["lua"]=>
>     int(1314007)
>     ["net"]=>
>     int(933888)
>     ["index"]=>
>     int(1097728)
>   }
> }

However, the following code:
```
$result = $client->executeUpdate('
    CREATE TABLE users ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255))
');
var_dump($result);
```
Throws an error
> [Tarantool\Client\Exception\CommunicationFailed] 
> Unable to read response length. (0)

It happends for me in both cases mbstring.func_overload = 2 and mbstring.func_overload = 0 . Don't you have any thoughts what else should i check?

Thank you!

**Comment by rybakit** [comment]
> It happends for me in both cases mbstring.func_overload = 2 and mbstring.func_overload = 0 . Don't you have any thoughts what else should i check?

Does it work if you execute this query in lua console? Try

```bash
docker exec -it <your-tarantool-container-id> sh
tarantoolctl connect 3301
``` 
and then follow this tutorial: https://www.tarantool.io/en/doc/2.1/tutorials/sql_tutorial/. Also, you could try to test it on Tarantool 2.1. I could debug it as well, but seems like you've already deleted your repo :)

**Comment by mikkiek** [comment]
> Does it work if you execute this query in lua console? Try

It's works without any issues in console. I will try to debug a little bit, maybe i've missed string manupulations without 8bit encoding.

> I could debug it as well, but seems like you've already deleted your repo :)

Yes, sorry. It's just for internal use. I'm not sure I can publish it, but at the same time I want to solve issues on our projects.

I will back when I find something.

**Comment by mikkiek** [comment]
Thank you for you help. 
It works not with Tarantool 2.1.2, 2.2.0 somehow doesn't work, i'll investigate it later.
At the moment I have last question: Don't you have a plan to add for Tarantool\Client\Connection\StreamConnection option which will handle custom Greeting class\object?
Coz' of "mbstring.func_overload" i should change your original file, i dind't find a way around.

**Comment by rybakit** [comment]
No, I don't plan to expose the `Greeting` class and would strongly recommend you to disable the function overloading as it will break every second library you have installed and will not work with the next versions of PHP anyway.

**Comment by mikkiek** [comment]
Unfortunately, I don't have a choice. CMS which is used on a project has requirement `mbstring.func_overload = 2 `
