### ISSUE TITLE
Persistent connection?

### ISSUE THREAD

**Issue by CthulhuDen** [tarantool-php/client#46]
Do you think it's possible to make use of persistent connections with this library for better performance and to prevent resource exhaustion? I made symfony 4 controller which only reads value from tarantool, and as I benchmark it it's performance over time degrades from over 1500 to some 400 req/s, and as some point it begins to error out with `Uncaught PHP Exception Tarantool\Client\Exception\ConnectionFailed: "Failed to connect to tcp://127.0.0.1:3301: Cannot assign requested address.`.

I tried to pass `STREAM_CLIENT_PERSISTENT` to `stream_socket_client`, but then it just can't read greetings anymore after first request.

**Comment by rybakit** [comment]
@CthulhuDen Could you test https://github.com/tarantool-php/client/pull/47?

**Comment by CthulhuDen** [comment]
@rybakit Thanks for your work, this seems to work like a charm!
