### ISSUE TITLE
Creating spaces

### ISSUE THREAD

**Issue by denismitr** [tarantool-php/client#48]
Hi, guys!

Is there a specific method to create a space and indexes. 
E.g. `$client->createSpace('some-space')`;

When I call `getSpace` on non-existent space, I get `Tarantool\Client\Exception\RequestFailed: Space 'some-space' does not exist`;

**Comment by rybakit** [comment]
Hi @denismitr! There is no such method in this client, so you need to make sure that space exists before retrieving it. To create a space you can either define it in an [instance file](https://www.tarantool.io/en/doc/2.1/book/admin/instance_config/), or at runtime with the `$client->evaluate()` method. Also, take a look at [tarantool/mapper](https://github.com/tarantool-php/mapper) library, it has already been [implemented](https://github.com/tarantool-php/mapper/blob/8bfe41b769ff5ff616ca859e7da6880f87fb5183/src/Schema.php#L43-L48) there.

**Comment by denismitr** [comment]
Thanks, mapper seems to have what I need
