### ISSUE TITLE
Replace don't support non-indexable fields

### ISSUE THREAD

**Issue by delef** [tarantool-php/client#49]
Hi!

I have some `cache` space with one indexable field (key). By example:
```
local cache = box.schema.create_space('cache')
cache:format({
  {name = 'key', type = 'string'},
})
cache:create_index('primary', {
  type = 'hash',
  parts = {{'key'}}
})
```

And I want replace some data:
```
$this->tarantool->getSpace('cache')->replace(['token:dcf59f14-0275-11e7-86fa-f7d003c26803', ['data' => ['foo' => 'bar']], 1563485380]);
```
After calling I see this exception:
**Type:** Tarantool\Client\Exception\RequestDenied
**Message:** Request "Tarantool\Client\Request\ReplaceRequest" is denied.
**File:** /path/to/vendor/tarantool/client/src/Exception/RequestDenied.php
**Line:** 22

But that works in Lua:
```
box.space.cache:replace({'token:dcf59f14-0275-11e7-86fa-f7d003c26803', { data =
 {foo = 'bar'} }, 1563485380});

---
- ['token:dcf59f14-0275-11e7-86fa-f7d003c26803', {'data': {'foo': 'bar'}},
  1563485380]
...

```

Thanks for your work!

**Comment by rybakit** [comment]
Hi @delef!
The `RequestDenied` exception can only be thrown by the [Firewall](https://github.com/tarantool-php/client/blob/master/src/Middleware/FirewallMiddleware.php) middleware. Make sure that you have allowed replace requests or remove the firewall if you don't need it.

**Comment by delef** [comment]
@rybakit Oh, sorry
