### ISSUE TITLE
possibility to bind params through LUA procedures?

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/client#53]
Hi,
I wonder if it is possible to bind parameters to a query through LUA calls.

I have this query working with php-client:
`$result = $client->executeUpdate("UPDATE {$this->table} SET expire_at = 0 WHERE resource_key = ? AND token = ? AND expire_at >= ?", $resource, $token, $expire_at);`

and I would actually like to run this query in a LUA procedure instead, something like:
```
//this param might not be the ideal but it is just an example:
$params = ['table' => 'key_locks', 'sql'=> 'UPDATE ? SET expire_at = 0 WHERE resource_key = ? AND token = ? AND expire_at >= ?', 'bind' = ['resource_key' => $resource, 'token' => $token, 'expire_at' => $expire_at]]
$result = $client->evaluate(
<<<LUA

    box.execute([[UPDATE ? SET expire_at = 0 WHERE resource_key = ? AND token = ? AND expire_at >= ?; ]])
    
    return 'success!'
LUA
, $params);
```
How can I output the sql string and the params to the LUA code with its bindings?
Thanks

**Comment by rybakit** [comment]
>  I would actually like to run this query in a LUA procedure instead,

In your example, you evaluate the LUA code instead of calling a procedure. This looks a bit weird to me and I can't see why one would prefer this approach over calling a stored procedure or executing SQL natively.

Regarding your question, here is an example of binding parameters using `evaluate` with `box.execute`:

```
$client->executeUpdate('DROP TABLE IF EXISTS users');

$client->executeUpdate('
    CREATE TABLE users ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255))
');

$client->executeUpdate('
    INSERT INTO users VALUES (null, :email1), (null, :email2)
',
    [':email1' => 'foo@example.com'],
    [':email2' => 'bar@example.com']
);

$params = ['foo@example.com', 1];

[$row] = $client->evaluate('
    return box.execute([[SELECT * FROM users WHERE "email" = ? AND "id" = ?;]], {...})
', ...$params);

var_dump($row['rows']);
```

P.S. Next time please post support questions on StackOverflow, it will make easier to other concerned developers to find answers to these questions in the future.

**Comment by zilveer** [comment]
@rybakit

"In your example, you evaluate the LUA code instead of calling a procedure. This looks a bit weird to me and I can't see why one would prefer this approach over calling a stored procedure or executing SQL natively."

- so when running `->evaluate` do you mean that it is not called as a procedure ?

I thought that by running `->evaluate` we are actually creating a temporary procedure which will be running on the Tarantool instance server ? 

Sure, what is the link to the StackOverflow?

Regards

**Comment by zilveer** [comment]
Btw I was asking this because I am trying to understand how Lua converts the params upon `... `

Thx
