### ISSUE TITLE
executeQuery generates an unknown Request type 11 fatal error

### ISSUE THREAD

**Issue by jcheron** [tarantool-php/client#56]
I created a space when I started the server:

```lua
space = box.schema.space.create('example')
space:create_index('primary', {type = 'tree', parts = {1, 'unsigned'}})
space:create_index('secondary', {type = 'tree', unique = false, parts = {2, 'str'}})
space:insert({1, 'foo'})
```
Data manipulation works correctly with `Space` query methods:
```php
$space = $client->getSpace('example');
echo \json_encode($space->select(Criteria::key([1])));
```

But any use of the `executeQuery` method in `SQL` generates a Fatal error:

```php
$res=$client->executeQuery('SELECT * FROM example');
```
>Fatal error: Uncaught Tarantool\Client\Exception\RequestFailed: Unknown request type 11 in RequestFailed.php:23 Stack trace: #0 /Handler/DefaultHandler.php(47): RequestFailed::fromErrorResponse(Object(Tarantool\Client\response))

`executeUpdate` method generates the same error:
```php
$result1 = $client->executeUpdate('
    CREATE TABLE users ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" VARCHAR(255))
');
```

I must have missed something somewhere.

### Versions
- Tarantool 1.10.3
- Client tarantool-php 0.5.2 
- PHP 7.3.6
- Debian stretch

**Comment by rybakit** [comment]
Tarantool 1.x doesn't support SQL, for SQL use version 2.x.

**Comment by jcheron** [comment]
It's okay with 2.2, Thanks!
I was misled by the readme that said:
>Tested on PHP 7.1-7.4 and Tarantool 1.7-2.2
