### ISSUE TITLE
get primary key field names

### ISSUE THREAD

**Issue by jcheron** [tarantool-php/client#57]
I read that there is no `information_schema` table in Tarantool (see https://www.tarantool.io/en/doc/2.2/book/sql/).
So I tried to make a method returning the names of the fields included in the primary key:

I would like to ask for the advice of specialists.

`$this->client` is an instance of `Client`

```php
public function getPrimaryKeys($spaceName)
{
	$idSpace = $this->getSpaceIdByName ( $spaceName );
	$indexesInfos = $this->client->getSpaceById ( Space::VINDEX_ID )->select ( Criteria::key ( [ $idSpace ] ) );
	$fieldsInfos = $this->client->getSpaceById ( Space::VSPACE_ID )->select ( Criteria::key ( [ $idSpace ] ) ) [0] [6];
	$pks = [ ];
	if ([ ] !== $fieldsInfos && ($firstIndex = \current ( $indexesInfos ))) {
		$indexedfields = $firstIndex [5];
		foreach ( $indexedfields as $field ) {
			$fieldNum = $field ['field'];
			if (isset ( $fieldsInfos [$fieldNum] )) {
				$pks [] = $fieldsInfos [$fieldNum] ['name'];
			}
		}
	}
	return $pks;
}
```

I tested with some spaces (without pk, and pk with 1 or more fields). It seems to work, but sometimes chance does things right (or wrong). 

What bothers me a little bit is the use of numerical indexes for arrays, it would be better to use named constants, these values may be referenced somewhere?

**Comment by rybakit** [comment]
>  these values may be referenced somewhere?

You can use [space:format()](https://www.tarantool.io/en/doc/2.2/book/box/box_space/#box-space-format) method to get an array of field names for the particular space. For example, calling `format()` on `_vspace` (id = 281) will return the following:

![tnt_vspace_format](https://user-images.githubusercontent.com/533861/62826862-99829700-bbc3-11e9-8143-56efc499d47f.png)

So, now you know that field `1` holds the owner and field `6` holds the format of the space ;)

P.S.

> $idSpace = $this->getSpaceIdByName ( $spaceName );

Btw, there is an easier way to get the space id by its name:

```php
$spaceId = $client->getSpace($spaceName)->getId();
```

**Comment by jcheron** [comment]
Thank you very much @rybakit !
- `space:format()` is very useful for the next step.
- `$client->getSpace($name)->getId()` is more appropriate, I hadn't seen the `getId` in the `Space` class...damn code completion!

issue ready for closing
