### ISSUE TITLE
fetch and return an associative array of datas

### ISSUE THREAD

**Issue by jcheron** [tarantool-php/client#58]
For compatibility reasons with other DBMS, I had to create a Tarantool Statement.
The statement is prepared from an SQL instruction.
We can bind parameters to it, and then retrieve the data.

In particular, I need a method that returns each line of the result as an associative array of field names and values (the equivalent of `FETCH_ASSOC` mode in `PDO` with `fetch` or `fetchAll`).

But with `SqlQueryResult`, data and metadata are separated. I am therefore forced to perform a processing operation to group them together.

I'm retrieving the field names:
`$this->queryResult` is an instance of `SqlQueryResult`.

```php
protected function getFields()
{
	$metas=$this->queryResult->getMetadata();
	$result=[];
	foreach ($metas as $meta){
		$result[]=\current($meta);
	}
	return $result;
}
```

I associate them with the data:

```php
protected function getDatas(){
	$datas=$this->queryResult->getData();
	$fields=$this->getFields();
	$result=[];
	foreach ($datas as $row){
		$resultRow=[];
		foreach ($row as $index=>$value){
			$resultRow[$fields[$index]]=$value;
		}
		$result[]=$resultRow;
	}
	return $result;
}
```
### Example of result
```
array (size=2)
  0 => 
    array (size=2)
      'id' => int 1
      'name' => string 'foo' (length=3)
  1 => 
    array (size=2)
      'id' => int 2
      'name' => string 'bar' (length=3)
```

It works fine. But I wonder if there's not another way to do that, less expensive for performance.

**Comment by rybakit** [comment]
Yes, there is a better way to do that. `SqlQueryResult` implements `Traversable` interface and therefore can be iterated. While iterating it will match field names from metadata with corresponding values from data:

```php
$rows = $client->executeQuery(...);
foreach ($rows as $row) {
    // $row is an accociative array in the format [
    //    "fieldName1" => value1,
    //    ...
    //    "fieldNameN" => valueN,
    // ]
}
```

And if you want to get the entire set as an array, you can do:

```php
$rowsArray = iterator_to_array($client->executeQuery(...));
```

**Comment by jcheron** [comment]
Thanks @rybakit !
It's indeed a better way
