### ISSUE TITLE
Tarantool-php client performances vs pdo/mysql

### ISSUE THREAD

**Issue by jcheron** [tarantool-php/client#59]
[Ubiquity-tarantool](https://github.com/phpMv/ubiquity-tarantool) is almost operational, but there are certainly some adjustments to be made.

I performed some benchmarks using [Techempower's multiple database queries test](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries) on my own servers, to appreciate the difference with pdo/mysql.

- In writing, it is very satisfying since `Ubiquity-Tarantool` is **9 times faster** than `Ubiquity-pdo`.
- In reading, the performances are similar, and that is my question: is this normal?

I performed benchmarks without Ubiquity, to appreciate the difference in reading between Tarantool and pdo/mysql.

### The results are as follows:
Reading of 20 rows on a table of 10,000 rows (php is pdo/mysql):

![image](https://user-images.githubusercontent.com/2511052/63435751-c3d81e00-c427-11e9-8ff9-219ccb310538.png)

The difference is even greater than with Ubiquity, which is partly explained by:
- the absence of persistent connection, and prepared statements
- the Loading of  22 Tarantool-php/client files vs 1 for pdo 
- or something I don't grasp...

![image](https://user-images.githubusercontent.com/2511052/63436822-b02db700-c429-11e9-8bee-b933f1e0f930.png)

### Server configuration
```lua
#!/usr/bin/env tarantool
-- Configure database
box.cfg {
   listen = 3302,
   background = true,
   log = '2.log',
   pid_file = '2.pid'
}
box.once("bootstrap", function()
   space = box.schema.space.create('world', {engine='vinyl'})
   space:format({
   {name = 'id', type = 'unsigned'},
   {name = 'randomNumber', type = 'string'}
   })
   box.schema.sequence.create('S',{min=1, start=1})
   space:create_index('primary', {
   type = 'tree',
   parts = {'id'},
   sequence= 'S'
   })
   box.schema.user.grant('guest', 'read,write,execute', 'space', 'world')
end)
```
### Page source code:
```php
\header('Content-type: application/json');
require_once 'vendor/autoload.php';

// Database connection
$client = \Tarantool\Client\Client::fromDsn ( 'tcp://127.0.0.1:3302' );

// Read number of queries to run from URL parameter
$query_count = 1;
if ($_GET['queries'] > 1) {
  $query_count = $_GET['queries'] > 500 ? 500 : $_GET['queries'];
}

// Create an array with the response string.
$arr = [];

// For each query, store the result set values in the response array
while (0 < $query_count--) {
  $query=$client->executeQuery('SELECT "id","randomNumber" FROM "world" WHERE "id" = ? limit 1', \mt_rand(1, 10000));
  // Store result in array.
  $arr[] = $query->getFirst();
}

// Use the PHP standard JSON encoder.
// http://www.php.net/manual/en/function.json-encode.php
echo \json_encode($arr);
```
### Page source code:

```php
\header('Content-type: application/json');

// Database connection
// http://www.php.net/manual/en/ref.pdo-mysql.php
$client = new \PDO('mysql:host=127.0.0.1;dbname=hello_world', 'userxxx', 'passwordxxx', [
    \PDO::ATTR_PERSISTENT => true,
    \PDO::ATTR_EMULATE_PREPARES => false
]);

// Read number of queries to run from URL parameter
$query_count = 1;
if ($_GET['queries'] > 1) {
  $query_count = $_GET['queries'] > 500 ? 500 : $_GET['queries'];
}

// Create an array with the response string.
$arr = [];

// Define query
$statement = $client->prepare('SELECT id,randomNumber FROM World WHERE id = ?');

// For each query, store the result set values in the response array
while (0 < $query_count--) {
  $statement->execute( [mt_rand(1, 10000)] );
  
  // Store result in array.
  $arr[] = $statement->fetch(PDO::FETCH_ASSOC);
}

// Use the PHP standard JSON encoder.
// http://www.php.net/manual/en/function.json-encode.php
echo \json_encode($arr);
```
## Configuration for tests
- Host
  - System : Linux debian 9.0 64 bits
  - Processor : Intel 1x Intel® C2350 (Avoton) 2 C / 2T @1.7 Ghz x64, VT-x, AES-NI
  - RAM : 4 Ghz DDR3
  - HD : SSD 120 Go
- Network
  - bandwidth : Unmetered 1 Gbit/sec - 2500BaseX interface
  - network card : 2.5 Gb/s
- Servers
  - Http : Apache/2.4 (Debian)
  - php : PHP 7.3
  - Databases : 
    - Ver 15.1 Distrib 10.1-MariaDB
    - Tarantool 2.2
    - 10 000 rows in DB

**Comment by rybakit** [comment]
> the absence of persistent connection, and prepared statements

Upcoming client release will have support for [persistent connections](https://github.com/tarantool-php/client#array-of-options), you can try it by installing the latest dev version: `composer install tarantool/client:@dev` 

> the Loading of 22 Tarantool-php/client files vs 1 for pdo

Doesn't matter if you use Opcache. Make sure you have it enabled and properly configured.

Apart from that I would recommend to use `memtx` instead of `vynil` (both engines are persistent, but `memtx` is faster).

Also note, that Tarantool's SQL implementation is still under active development, there are a lot of [optimizations](https://github.com/tarantool/tarantool/issues?q=is%3Aissue+is%3Aopen+sql+label%3Aperformance) planned. In that regard I would suggest running your benchmark using the [binary protocol](https://github.com/tarantool-php/client#binary-protocol) and compare results with the SQL ones (in my tests SQL ~2 times slower than the binary equivalent).

Another option to inmprove the performance is to make calls asynchrouniusly with `ext-async` or `ext-swoole` (according to my benchmars, you can gain 3x boost in performance).

I will publish by benchmark results soon in [this](https://github.com/tarantool-php/benchmarks) repo.

**Comment by jcheron** [comment]
Thank you for all these answers @rybakit 

On this test and with my configuration:
- It is indeed better with a persistent connection ( ~5%)
- I did not see any influence of the storage engine (`memtx` or `vinyl`).
- The binary protocol is also more efficient than SQL (~15%)

But I can't use it with `Ubiquity`, since ORM is based on the relational model and SQL (the objective was to be able to switch from pdo/* to Tarantool in a transparent way, without the developer having to change his code).

Rq:
I don't quite agree on the effects of the number of files included. OPCache reduces the effect of multiple inclusions, but does not completely annihilate it (I did a special `php-22` test where I included with pdo the 21 additional files required by Tarantool).
OPCache is well activated and configured on my test server.

### Results
![image](https://user-images.githubusercontent.com/2511052/63477801-3f1cec80-c487-11e9-9a74-cf9d31988079.png)

- tarantool => memtx +SQL
- php-22 => pdo/mysql + 21 include for Tarantool files
- tarantool-persist => memtx +SQL + persistent connection
- php => pdo/mysql
- tarantool-bi => memtx + binary protocol
- tarantool-bi-persist => memtx + binary protocol +peristent connection

### Ubiquity-tarantool results
So I did the benchmarks again in reading for Ubiquity, with memtx and persistent connection.

It's better:-)
in particularly for throughput (+11%), more variable for execution time

![image](https://user-images.githubusercontent.com/2511052/63478982-63c79300-c48c-11e9-8dad-a6b950b167b9.png)

I'll try with `Swoole` to see how it goes.

**Comment by jcheron** [comment]
Hi @rybakit 
Here are the results of the tests with Swoole:
I always use the same tests (Techempower multiple writing and reading), however, the test server has changed, so do not compare these results with the previous ones, in absolute value.

- ubi-swoole-tarantool => Ubiquity + Swoole + Tarantool + Coroutine
- ubi-tarantool => Ubiquity + Tarantool + Apache
- ubi-swoole-pool => Ubiquity + Swoole + Mysql coroutine
- ubi-swoole => Ubiquity + Swoole +pdo
- ubi-pdo => Ubiquity + Apache + pdo
- ubi-swoole-mysqli => Ubiquity + Swoole + Mysqli + Coroutine

All tests are performed with 20 consecutive queries.

### In writing:
Tarantool was already very fast, it is even faster

![image](https://user-images.githubusercontent.com/2511052/64083254-f550c380-cd1c-11e9-8f30-937102d3317b.png)

### In reading:
I made several tentatives with Tarantool, connection pool, small groups  of asynchronous queries in a coroutine...
These tests did not yield anything, I think that on this kind of tests (repeated single queries), you can't gain the 3X in performance..

So I came back to the simplest solution, Swoole + coroutine activation: which gives quite acceptable results with Tarantool, which is as fast as **Swoole Coroutine Mysql**.
Don't forget that I only use SQL (and not the binary protocol).

![image](https://user-images.githubusercontent.com/2511052/64083556-ae190180-cd21-11e9-9332-c2b454053e92.png)

Are the results of your benchmarks in this direction?

**Comment by jcheron** [comment]
I was a little pessimistic about the reading performance:
With a connection pool, and execution of queries in 5 groups of 4, the results are much better. 
[edit]
With a properly adjusted connection pool,
I now have fully satisfactory results, and we have more than 3X on the execution time (2.36 -> 0.73 ms), you were right 👍 
[/edit]
### Reading bench (20 queries)
![image](https://user-images.githubusercontent.com/2511052/64212681-7b4e4500-ceaa-11e9-9a62-901633be4895.png)

**Comment by rybakit** [comment]
@jcheron I have released a [new version](https://github.com/tarantool-php/client/releases/tag/v0.6.0) with minor optimizations and published [benchmark results](https://github.com/tarantool-php/benchmarks#results) (up to 5x boost in those synthetic benchmarks).

Also, please note that unlike MySQL, Tarantool is single-threaded and to leverage more CPU cores it's recommended to run multiple Tarantool instances on the same server.

And the good news about the SQL performance is that the upcoming Tarantool version will have support for [prepared statements](https://github.com/tarantool/tarantool/commit/ff2091e09b5a7e9b7aa3f3e996dc7a06189889f3).

**Comment by jcheron** [comment]
That's good news, thank you !
I'm going to look at this closely.
