### ISSUE TITLE
Multiple insertion of rows in a single transaction

### ISSUE THREAD

**Issue by yapro** [tarantool-php/client#65]
Please, say, can I insert many rows in a one transaction.

**Comment by rybakit** [comment]
There are 2 options to do so:

1) You can create a Lua function that accepts and inserts multiple rows atomically and invoke it from the client via the `call()` method. For inspiration, check out this [example](https://github.com/tarantool-php/queue#custom-methods) from the [tarantool/queue](https://github.com/tarantool-php/queue) library, which shows how to insert multiple tasks into the queue in one call.
2) You can use the SQL `INSERT` statement with multiple comma-separated lists of values, check out this [example](https://github.com/tarantool-php/client/blob/master/examples/protocol/execute.php#L25-L30) for details.

For other support questions like this, please use the official Telegram channel (either [Russian](https://teleg.run/tarantoolru) or [English](https://teleg.run/tarantool)) or/and [StackOverflow](https://stackoverflow.com/questions/tagged/tarantool).
