### ISSUE TITLE
Why not Symfony/uid ^7

### ISSUE THREAD

**Issue by terehov-space** [tarantool-php/client#96]
<img width="1689" alt="image" src="https://github.com/tarantool-php/client/assets/71380522/95b70419-5cd1-404a-9eb6-f9922a2c156e">

Cant't use package over Laravel v11, cause of dependencies of this package 

Tested with version 7.1.1 over editing code. It's absolutely normally works

**Comment by rybakit** [comment]
Fixed via https://github.com/tarantool-php/client/pull/97
